services:
  workbot:
    container_name: workbot
    build: .
    restart: unless-stopped
    networks:
      nginx_net:
    env_file:
      - .env
    volumes:
      - ./src/logs:/src/logs
      - ./src/bot/logs:/src/bot/logs

  redis_:
    container_name: redis_
    image: redis:8.0-alpine3.21
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      nginx_net:
    volumes:
      - ./src/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis_data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]



volumes:
  redis_data:

networks:
  nginx_net:
    name: nginx_net
    driver: bridge
#    external: true
#workbot  | Downloading ruff (10.7MiB)
#workbot  |  Downloaded ruff
#workbot  | Installed 1 package in 28ms
#workbot  | Bytecode compiled 3947 files in 173ms
#workbot  | 2026-04-05 13:07:25.902 | INFO     | src.config.conf:get_connection:96 - Redis подключён
#workbot  | INFO:apscheduler.scheduler:Scheduler started
