name: CI/CD ProdApi dev

on:
  push:
    branches: [ dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_SERVER_F_TWEB }}
          username: ${{ secrets.SERVER_USER_F_TWEB }}
          key: ${{ secrets.MINZKHBOT_F_TWEB }}
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/tweb_git
            ssh -T git@github.com
            cd /home/My/WorkBot
            git pull
            docker compose down
            docker compose up -d --build
#            docker compose restart
# todo Написать хендлер для отлова сообщений в чат "отправка приглашений" или как я его там назвал
# todo потом pandas или текст определиться, может быть сделать оба, посмотреть сложно ли будет
# todo ну и потестить эту херобору всю
# апдейт деплой